import { registerAs } from '@nestjs/config';

export default registerAs('app', () => ({
  name: process.env.APP_NAME || 'api-gateway',
  port: parseInt(process.env.PORT || '3000', 10),
  authServiceUrl: process.env.AUTH_SERVICE_URL || 'http://localhost:3001',
  authServiceTcpHost: process.env.AUTH_SERVICE_TCP_HOST || '127.0.0.1',
  authServiceTcpPort: parseInt(process.env.AUTH_SERVICE_TCP_PORT || '4001', 10),
  userServiceUrl: process.env.USER_SERVICE_URL || 'http://localhost:3002',
  userServiceTcpHost: process.env.USER_SERVICE_TCP_HOST || '127.0.0.1',
  userServiceTcpPort: parseInt(process.env.USER_SERVICE_TCP_PORT || '4002', 10),
  productServiceUrl: process.env.PRODUCT_SERVICE_URL || 'http://localhost:3003',
  productServiceTcpHost: process.env.PRODUCT_SERVICE_TCP_HOST || '127.0.0.1',
  productServiceTcpPort: parseInt(process.env.PRODUCT_SERVICE_TCP_PORT || '4003', 10),
  inventoryServiceUrl: process.env.INVENTORY_SERVICE_URL || 'http://localhost:3004',
  inventoryServiceTcpHost: process.env.INVENTORY_SERVICE_TCP_HOST || '127.0.0.1',
  inventoryServiceTcpPort: parseInt(process.env.INVENTORY_SERVICE_TCP_PORT || '4004', 10),
  cartServiceUrl: process.env.CART_SERVICE_URL || 'http://localhost:3005',
  cartServiceTcpHost: process.env.CART_SERVICE_TCP_HOST || '127.0.0.1',
  cartServiceTcpPort: parseInt(process.env.CART_SERVICE_TCP_PORT || '4005', 10),
  orderServiceUrl: process.env.ORDER_SERVICE_URL || 'http://localhost:3006',
  orderServiceTcpHost: process.env.ORDER_SERVICE_TCP_HOST || '127.0.0.1',
  orderServiceTcpPort: parseInt(process.env.ORDER_SERVICE_TCP_PORT || '4006', 10),
  paymentServiceUrl: process.env.PAYMENT_SERVICE_URL || 'http://localhost:3007',
  paymentServiceTcpHost: process.env.PAYMENT_SERVICE_TCP_HOST || '127.0.0.1',
  paymentServiceTcpPort: parseInt(process.env.PAYMENT_SERVICE_TCP_PORT || '4007', 10),
  shippingServiceUrl: process.env.SHIPPING_SERVICE_URL || 'http://localhost:3008',
  shippingServiceTcpHost: process.env.SHIPPING_SERVICE_TCP_HOST || '127.0.0.1',
  shippingServiceTcpPort: parseInt(process.env.SHIPPING_SERVICE_TCP_PORT || '4008', 10),
  promotionServiceUrl: process.env.PROMOTION_SERVICE_URL || 'http://localhost:3009',
  promotionServiceTcpHost: process.env.PROMOTION_SERVICE_TCP_HOST || '127.0.0.1',
  promotionServiceTcpPort: parseInt(process.env.PROMOTION_SERVICE_TCP_PORT || '4009', 10),
  reviewServiceUrl: process.env.REVIEW_SERVICE_URL || 'http://localhost:3010',
  reviewServiceTcpHost: process.env.REVIEW_SERVICE_TCP_HOST || '127.0.0.1',
  reviewServiceTcpPort: parseInt(process.env.REVIEW_SERVICE_TCP_PORT || '4010', 10),
}));
